const genres = [ "acoustic", 
   "afrobeat", 
   "alt-rock", 
   "alternative", 
   "ambient", 
   "bluegrass", 
   "blues", 
   "bossanova", 
   "brazil", 
   "breakbeat", 
   "chicago-house", 
   "children", 
   "chill", 
   "classical", 
   "club", 
   "comedy", 
   "country", 
   "dance", 
   "dancehall", 
   "deep-house", 
   "disco", 
   "disney", 
   "drum-and-bass", 
   "dubstep", 
   "electronic", 
   "emo", 
   "folk", 
   "funk", 
   "garage", 
   "gospel", 
   "goth", 
   "groove", 
   "grunge", 
   "guitar", 
   "hard-rock", 
   "heavy-metal", 
   "hip-hop", 
   "holidays", 
   "honky-tonk", 
   "house", 
   "indian", 
   "indie", 
   "indie-pop", 
   "jazz", 
   "k-pop", 
   "kids", 
   "latin", 
   "metal",
   "new-age", 
   "new-release", 
   "opera", 
   "party",
   "piano", 
   "pop",
   "progressive-house",
   "punk", 
   "punk-rock", 
   "r-n-b", 
   "reggae", 
   "reggaeton", 
   "rock", 
   "rock-n-roll",
   "salsa",
   "samba",
   "show-tunes",
   "ska",
   "soul",
   "soundtracks",
   "study",
   "tango",
   "techno",
   "trance",
   "trip-hop",
   "work-out",
   "world-music"
]

function capitalizeFirstLetter(string) {
   return string.charAt(0).toUpperCase() + string.slice(1);
}

const allGenres = genres.map(genre => {
   return capitalizeFirstLetter(genre);  
})

export default allGenres;