const seed_data = [
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   },
   {
      acousticness: '',
      danceability: '',
      energy: '',
      instrumentalness: '',
      key: '',
      liveness: '',
      loudness: '',
      mode: '',
      popularity: '',
      speechiness: '',
      tempo: '',
      signature: '',
      valence: '',
      duration: '',
   }
]
export default seed_data;